### PR TITLE
Add response handling functions

### PR DESCRIPTION
**Pull request by bwestlin**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

Add support functions for parsing responses for requests made with `Request`'s from the `profanity_check_request` & `profanity_replace_request` functions.
Update example using response parse function as well.

**Update**: Shall we bump version in this PR as well?

### CODE REVIEW

**Review by vojd — APPROVED** [review]
Thank you for these additions <3

**Comment by vojd** [comment]
Yes lets bump the version in this PR

**Comment by bwestlin** [comment]
Good to go, but looks like you need to do the merge

**Comment by vojd** [comment]
Ok there we go. Now you should be allowed to merge this branch. But before you do. Can you add the changes to `CHANGELOG.md` as well? Then we can make a new release.

**Pull request merged**
